### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by jozemanue** [dvcol/synology-download#136]
### Description

Hello, I connect the plugin with my synology user account which using type "two-factor" security. Everything works fine, until I restart the computer and it asks me to log in again (although I already have the "remember my device",  "automatic login" and "remember me" option checked)

### Affected part

- [X ] Connection settings

### Screenshots or Mock up

![image](https://user-images.githubusercontent.com/60007170/193572218-d80496b5-02c2-4deb-a545-2ee96a9ffe3e.png)

### Steps to Reproduce the Issue

Every time I turn on the computer and open chrome, I have to log in again with the "two-factor" code.

### Failure Logs

I don't know exactly what to copy here

### Versions

**Pluging Version**: Version: 1.14.6
**Browser version**: Google Crhome Versión 105.0.5195.127 (Build oficial) (64 bits)
**DSM version**: DSM 7.1.1-42962 Update 1
--

**Comment by dvcol** [comment]
Some fixes for login behavior will be included in the next release.

This might solve it, but 2FA and quickconnect are finicky to implement with Synology's API.

I'm closing this for now, but if the issue persist, please fell free to re-open with mode details.

Note that due to limitation with service worker access to unseure urls, if you are using https, you either need to install a valid certificate, or open the popup in between restart or extension update.
