### ISSUE TITLE
[feature]: Add multiple links in a "download Basket" to group downloads

### ISSUE THREAD

**Issue by gregmzs** [dvcol/synology-download#201]
### Affected part

Context menu (right click on links)

### Description

It would be great to be able to add multiple urls with context menu (add to multiple downloads), and to be able to launch downloads with the download popup with all links added per line in links area.

It could be 3 new entries in context menu :
1. Add to multiple downloads
2. Launch multiple downloads (which open start download popup with all links in download textarea)
3. Reset multiple downloads (clear current selection)

Thanks a lot

**Comment by dvcol** [comment]
I've pushed an update that allows peristence of task form.

If you add to a modal with this option toggled, url will be added to the modal instead of replacing it.

Hope this addresses your need.

I'll close this issue, but if you think this doesn't solve your use case, please feel free to re-open it :)
