### ISSUE TITLE
Bugs Maybe

### ISSUE THREAD

**Issue by BatangTurun** [dvcol/synology-download#203]
More annoyance than bugs:

1) After some inactivity and then adding new task a Log in required message appears, just clicking on the extension icon in the browser tool bar to display the tasks remedies this.

2) Since updating to version 2.2.1 any download from withing the browser appears as a completed task even though it is not downloaded by Download Station. 

Microsoft Edge - Version 111.0.1661.41 (Official build) (64-bit)
Download Station (client for Synology NAS) – Version 2.2.0
DSM 6.2.4-25556 Update 6
Connection - HTTP

![Untitled - 1](https://user-images.githubusercontent.com/13508405/228533856-8de5d95d-5b1f-4fbe-955a-e18b20ebaee1.jpg)

**Comment by dvcol** [comment]
Hello, thanks for taking the time to create an issue !

Concerning your two concerns, here some info that could be of help:

1. for the auto-login issue:

If you are using HTTPS to connect without adding a valid SSL certificate, a limitation of MV3 is that service worker (the background task that runs the extension) is forced to sleep and as such looses authentication to the server.

This requires to re-log from the popup (as service worker don't have valid dom instances) to re-establish connection.

This is tracked [here](https://github.com/dvcol/synology-download/issues/183), before the issue was also present but the extension failed silently (which could brake functionality without the user noticing).

2. for the local downloads:

I've recently added an implementation for local download management as well as download interception (to support more than magnet links and enable transferring local download to the remote nas).

If you do not want to enable those functionalities, you can already disable them in their dedicated settings:

![image](https://user-images.githubusercontent.com/17250935/228625065-0c0dc179-5c82-4381-a170-07b5f7d62b3a.png)


Hope that helps :)

**Comment by dvcol** [comment]
I've just seen that you connect through HTTP, which should only force a auto-login when the background times-out.

When no active tab is running for more than 5 minutes, the same issue as HTTPs occurs, the service worker is shutdown and we need either to open a new tab (any new tab re-awaken the service) or open the modal.

This is also a limitation of MV3 imposed by chrome sadly (which is quite controversial at the moment), which is exacerbated by the recent changes to chrome which put inactive tabs to sleep to save memory.

Hopefully the chrome team changes it's mind on this, but until then sadly, nothing much can be done.

**Comment by BatangTurun** [comment]
Thanks for the feedback.

I will now close this, thanks again.
