### ISSUE TITLE
[feature]: Feature Request (please change this title)

### ISSUE THREAD

**Issue by Fungusware** [dvcol/synology-download#216]
### Affected part

General Options/Settings

### Description

Would be great to be able to set the default download location, so we don't have to select it every time.

**Comment by dvcol** [comment]
Closing this, because you can already select the default location either through the `quick menu` / `context menu` settings:

![image](https://github.com/dvcol/synology-download/assets/17250935/474bddb9-7d8a-4d80-ada9-a1a38f4719a8)

Or through you synology download settings directly (depending on you account permissions)

![image](https://github.com/dvcol/synology-download/assets/17250935/3484867e-b0b7-4c33-821e-ec0edc109707)
