### ISSUE TITLE
[feature]: Change priority in files and tasks

### ISSUE THREAD

**Issue by dvcol** [dvcol/synology-download#61]

**Comment by valichek** [comment]
Thank you, plugin is very useful.
One thing is really missing is partial download of torrent content, mean possibility to select files from torrent for download.
Does this issue includes the described feature?

**Comment by dvcol** [comment]
Yes this is what this issue is tracking. However I didn' tmanage to find documentation on the API for partial download / download priority.

I've seen other third party do this kind of functioanilities, so the api must exist, but without documentaiton it's hard to implement.

Any help or info on this would be welcome :)

**Comment by nik684** [comment]
Hi. I'm also interested in this feature.
Unfortunately I have zero knowledge of developing on this language but here is my humble try to help a bit.
I suppose you already know this API doc. Maybe it's outdated.
https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/DownloadStation/All/enu/Synology_Download_Station_Web_API.pdf

There is some "Task_file" object that has "priority" member.
Since I found it in 5 minutes I guess you already know that. Anyway, great plugin (actually the best for DS). Thank you!

**Comment by dvcol** [comment]
Hello, yes this is a very old and outdated documentation sadly (last edited 2012 last published 2014)

however I managed to patch something by mimicking the api calls from dem web interface.

 Or exactly orthodox but in the absence of proper documentation it’s the best I can do.

it should be available in [release 2.0.0](https://github.com/dvcol/synology-download/releases/tag/v2.0.0) and onwards

**Comment by dvcol** [comment]
If you enjoy the extension, please leave a review in the webstore, it helps with discovery :)
